### ISSUE TITLE
How to destroy/garbage collect JVM after connect?

### ISSUE THREAD

**Issue by syahiaoui** [CraZySacX/node-jdbc#142]
The jvm takes a lot of memory of the blow I would be well deleted it after recovering the connection!!

```json
{
  "monit": {
    "memory": "403M",
    "cpu": 0
  },
  "name": "TERADATA",
```

If there is a solution, is this not going to cause problems when calling a purge function and re-initilase connection?

Best regards

**Comment by CraZySacX** [comment]
I would suggest hooking up to the VM with VisualVM (or another similar tool), grabbing a heap dump and seeing which objects are taking up so much memory.   The connection objects shouldn't be consuming that much memory (unless they are leaked by the pool somehow).   The resultsets can consume a ton of memory, but those should be garbage collected when closed.

As for forcing a garbage collect, its hard (see https://stackoverflow.com/questions/1481178/how-to-force-garbage-collection-in-java).   You can turn the GC parameters for your particular setup however.

I'm closing this for now.   Feel free to re-open if you discover the leaked objects are due to node-jdbc not cleaning up resources correctly.
