### ISSUE TITLE
Broken decimals

### ISSUE THREAD

**Issue by vprus** [CraZySacX/node-jdbc#160]
If my SQL query returns decimals, all I get in JS is an empty objects. What appears to be is that:

- ResultSet.prototype.toObjectIter calls java's ResultSet.getBigDecimalSync, which returns BigDecimal
- BigDecimal does not have any public fields, and becomes empty JS object.
- If I add `java.callMethodSync(value, "doubleValue")` I do see a valid-looking value, and it seems to me that what should be done by default, since empty objects are completely useless.

**Comment by CraZySacX** [comment]
This is correct behavior.   The default java types for NUMERIC and DECIMAL columns are BigDecimal.  You are getting back a javascript wrapper object around 'BigDecimal', generated by node-java.

I can't default to calling the `doubleValue` method on the BigDecimal, because that may restrict usability.   The intent is to give you as much flexibility with the java object as possible.
