### ISSUE TITLE
running two different jdbc connections: classpath hell?

### ISSUE THREAD

**Issue by OwenBrotherwood** [CraZySacX/node-jdbc#35]
I need to run two jdbc connections under the same node.js: one for DB2 and the other for Sybase.

This may not be supported ? as it seems that when I have both defineded, then one of the drivers gives java.lang.NoClassDefFoundError.

ie
var sybase = new (require('jdbc');
var sybaseConfig = {
//<configuration>
};
var db2 = new (require('jdbc'));
var db2Config = {
//<configuration>
};

// followed by initialize and open of the two 
// I have commented out the one and then the other, both work if the other is not present

**Comment by ganna-shmatova** [comment]
I am seeing this also with my test cases

![image](https://cloud.githubusercontent.com/assets/7226694/9198976/ae1f928e-400d-11e5-8cc8-62ea9a81d35c.png)

**Comment by CraZySacX** [comment]
I'll try and see if I can reproduce this, but module wasn't built with multiple db back ends in mind.  It would be beneficial however.

**Comment by ganna-shmatova** [comment]
I found an odd way around it...

Turns out if you bind the .jar files on the first call calling the other dbs works fine.

however, if you bind only the jar you're using, then bind another .jar & try to access a path within it, it bugs up saying path does not exist.

(relatedly, all the classpaths I ever add get appended over and over and over again to the java module. This is going to cause an eventual overflow if the app runs long enough...)

**Comment by CraZySacX** [comment]
Only one JVM instance is created by node-java.  And once the JVM has been created, adding to the classpath has no effect.  So in the case of node-jdbc, the first time initialize is called, the classpath is set, and the JVM is spun up when putSync is called the first time.   This means your workaround of setting all the jars necessary before the first initialized call is in fact the only way to do this.  I'll have to rework setup so that dbs are managed independently from the java instance.

**Comment by OwenBrotherwood** [comment]
Thankyou :+1:
